// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: machinetalk/protobuf/emcclass.proto

package pb;

public final class Emcclass {
  private Emcclass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PmCartesianOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.PmCartesian)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double x = 10;</code>
     */
    boolean hasX();
    /**
     * <code>optional double x = 10;</code>
     */
    double getX();

    /**
     * <code>optional double y = 20;</code>
     */
    boolean hasY();
    /**
     * <code>optional double y = 20;</code>
     */
    double getY();

    /**
     * <code>optional double z = 30;</code>
     */
    boolean hasZ();
    /**
     * <code>optional double z = 30;</code>
     */
    double getZ();
  }
  /**
   * Protobuf type {@code pb.PmCartesian}
   */
  public static final class PmCartesian extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.PmCartesian)
      PmCartesianOrBuilder {
    // Use PmCartesian.newBuilder() to construct.
    private PmCartesian(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PmCartesian(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PmCartesian defaultInstance;
    public static PmCartesian getDefaultInstance() {
      return defaultInstance;
    }

    public PmCartesian getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PmCartesian(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 81: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 161: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
            case 241: {
              bitField0_ |= 0x00000004;
              z_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Emcclass.internal_static_pb_PmCartesian_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Emcclass.internal_static_pb_PmCartesian_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Emcclass.PmCartesian.class, pb.Emcclass.PmCartesian.Builder.class);
    }

    public static com.google.protobuf.Parser<PmCartesian> PARSER =
        new com.google.protobuf.AbstractParser<PmCartesian>() {
      public PmCartesian parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PmCartesian(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PmCartesian> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 10;
    private double x_;
    /**
     * <code>optional double x = 10;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double x = 10;</code>
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 20;
    private double y_;
    /**
     * <code>optional double y = 20;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double y = 20;</code>
     */
    public double getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 30;
    private double z_;
    /**
     * <code>optional double z = 30;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double z = 30;</code>
     */
    public double getZ() {
      return z_;
    }

    private void initFields() {
      x_ = 0D;
      y_ = 0D;
      z_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(10, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(20, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(30, z_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(20, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(30, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pb.Emcclass.PmCartesian parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Emcclass.PmCartesian parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Emcclass.PmCartesian parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Emcclass.PmCartesian parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Emcclass.PmCartesian parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Emcclass.PmCartesian parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pb.Emcclass.PmCartesian parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pb.Emcclass.PmCartesian parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pb.Emcclass.PmCartesian parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Emcclass.PmCartesian parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pb.Emcclass.PmCartesian prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.PmCartesian}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.PmCartesian)
        pb.Emcclass.PmCartesianOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Emcclass.internal_static_pb_PmCartesian_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Emcclass.internal_static_pb_PmCartesian_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Emcclass.PmCartesian.class, pb.Emcclass.PmCartesian.Builder.class);
      }

      // Construct using pb.Emcclass.PmCartesian.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Emcclass.internal_static_pb_PmCartesian_descriptor;
      }

      public pb.Emcclass.PmCartesian getDefaultInstanceForType() {
        return pb.Emcclass.PmCartesian.getDefaultInstance();
      }

      public pb.Emcclass.PmCartesian build() {
        pb.Emcclass.PmCartesian result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Emcclass.PmCartesian buildPartial() {
        pb.Emcclass.PmCartesian result = new pb.Emcclass.PmCartesian(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Emcclass.PmCartesian) {
          return mergeFrom((pb.Emcclass.PmCartesian)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Emcclass.PmCartesian other) {
        if (other == pb.Emcclass.PmCartesian.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Emcclass.PmCartesian parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Emcclass.PmCartesian) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double x_ ;
      /**
       * <code>optional double x = 10;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double x = 10;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>optional double x = 10;</code>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double x = 10;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>optional double y = 20;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double y = 20;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>optional double y = 20;</code>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double y = 20;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }

      private double z_ ;
      /**
       * <code>optional double z = 30;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double z = 30;</code>
       */
      public double getZ() {
        return z_;
      }
      /**
       * <code>optional double z = 30;</code>
       */
      public Builder setZ(double value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double z = 30;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.PmCartesian)
    }

    static {
      defaultInstance = new PmCartesian(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.PmCartesian)
  }

  public interface EmcPoseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.EmcPose)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .pb.PmCartesian tran = 10;</code>
     */
    boolean hasTran();
    /**
     * <code>required .pb.PmCartesian tran = 10;</code>
     */
    pb.Emcclass.PmCartesian getTran();
    /**
     * <code>required .pb.PmCartesian tran = 10;</code>
     */
    pb.Emcclass.PmCartesianOrBuilder getTranOrBuilder();

    /**
     * <code>optional double a = 20;</code>
     */
    boolean hasA();
    /**
     * <code>optional double a = 20;</code>
     */
    double getA();

    /**
     * <code>optional double b = 30;</code>
     */
    boolean hasB();
    /**
     * <code>optional double b = 30;</code>
     */
    double getB();

    /**
     * <code>optional double c = 40;</code>
     */
    boolean hasC();
    /**
     * <code>optional double c = 40;</code>
     */
    double getC();

    /**
     * <code>optional double u = 50;</code>
     */
    boolean hasU();
    /**
     * <code>optional double u = 50;</code>
     */
    double getU();

    /**
     * <code>optional double v = 60;</code>
     */
    boolean hasV();
    /**
     * <code>optional double v = 60;</code>
     */
    double getV();

    /**
     * <code>optional double w = 70;</code>
     */
    boolean hasW();
    /**
     * <code>optional double w = 70;</code>
     */
    double getW();
  }
  /**
   * Protobuf type {@code pb.EmcPose}
   */
  public static final class EmcPose extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.EmcPose)
      EmcPoseOrBuilder {
    // Use EmcPose.newBuilder() to construct.
    private EmcPose(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EmcPose(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EmcPose defaultInstance;
    public static EmcPose getDefaultInstance() {
      return defaultInstance;
    }

    public EmcPose getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EmcPose(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 82: {
              pb.Emcclass.PmCartesian.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = tran_.toBuilder();
              }
              tran_ = input.readMessage(pb.Emcclass.PmCartesian.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tran_);
                tran_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 161: {
              bitField0_ |= 0x00000002;
              a_ = input.readDouble();
              break;
            }
            case 241: {
              bitField0_ |= 0x00000004;
              b_ = input.readDouble();
              break;
            }
            case 321: {
              bitField0_ |= 0x00000008;
              c_ = input.readDouble();
              break;
            }
            case 401: {
              bitField0_ |= 0x00000010;
              u_ = input.readDouble();
              break;
            }
            case 481: {
              bitField0_ |= 0x00000020;
              v_ = input.readDouble();
              break;
            }
            case 561: {
              bitField0_ |= 0x00000040;
              w_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Emcclass.internal_static_pb_EmcPose_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Emcclass.internal_static_pb_EmcPose_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Emcclass.EmcPose.class, pb.Emcclass.EmcPose.Builder.class);
    }

    public static com.google.protobuf.Parser<EmcPose> PARSER =
        new com.google.protobuf.AbstractParser<EmcPose>() {
      public EmcPose parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmcPose(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EmcPose> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TRAN_FIELD_NUMBER = 10;
    private pb.Emcclass.PmCartesian tran_;
    /**
     * <code>required .pb.PmCartesian tran = 10;</code>
     */
    public boolean hasTran() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .pb.PmCartesian tran = 10;</code>
     */
    public pb.Emcclass.PmCartesian getTran() {
      return tran_;
    }
    /**
     * <code>required .pb.PmCartesian tran = 10;</code>
     */
    public pb.Emcclass.PmCartesianOrBuilder getTranOrBuilder() {
      return tran_;
    }

    public static final int A_FIELD_NUMBER = 20;
    private double a_;
    /**
     * <code>optional double a = 20;</code>
     */
    public boolean hasA() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double a = 20;</code>
     */
    public double getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 30;
    private double b_;
    /**
     * <code>optional double b = 30;</code>
     */
    public boolean hasB() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double b = 30;</code>
     */
    public double getB() {
      return b_;
    }

    public static final int C_FIELD_NUMBER = 40;
    private double c_;
    /**
     * <code>optional double c = 40;</code>
     */
    public boolean hasC() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double c = 40;</code>
     */
    public double getC() {
      return c_;
    }

    public static final int U_FIELD_NUMBER = 50;
    private double u_;
    /**
     * <code>optional double u = 50;</code>
     */
    public boolean hasU() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double u = 50;</code>
     */
    public double getU() {
      return u_;
    }

    public static final int V_FIELD_NUMBER = 60;
    private double v_;
    /**
     * <code>optional double v = 60;</code>
     */
    public boolean hasV() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double v = 60;</code>
     */
    public double getV() {
      return v_;
    }

    public static final int W_FIELD_NUMBER = 70;
    private double w_;
    /**
     * <code>optional double w = 70;</code>
     */
    public boolean hasW() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double w = 70;</code>
     */
    public double getW() {
      return w_;
    }

    private void initFields() {
      tran_ = pb.Emcclass.PmCartesian.getDefaultInstance();
      a_ = 0D;
      b_ = 0D;
      c_ = 0D;
      u_ = 0D;
      v_ = 0D;
      w_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTran()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(10, tran_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(20, a_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(30, b_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(40, c_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(50, u_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(60, v_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(70, w_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, tran_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(20, a_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(30, b_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(40, c_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(50, u_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(60, v_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(70, w_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pb.Emcclass.EmcPose parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Emcclass.EmcPose parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Emcclass.EmcPose parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Emcclass.EmcPose parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Emcclass.EmcPose parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Emcclass.EmcPose parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pb.Emcclass.EmcPose parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pb.Emcclass.EmcPose parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pb.Emcclass.EmcPose parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Emcclass.EmcPose parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pb.Emcclass.EmcPose prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.EmcPose}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.EmcPose)
        pb.Emcclass.EmcPoseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Emcclass.internal_static_pb_EmcPose_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Emcclass.internal_static_pb_EmcPose_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Emcclass.EmcPose.class, pb.Emcclass.EmcPose.Builder.class);
      }

      // Construct using pb.Emcclass.EmcPose.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTranFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (tranBuilder_ == null) {
          tran_ = pb.Emcclass.PmCartesian.getDefaultInstance();
        } else {
          tranBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        b_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        c_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        u_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        v_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        w_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Emcclass.internal_static_pb_EmcPose_descriptor;
      }

      public pb.Emcclass.EmcPose getDefaultInstanceForType() {
        return pb.Emcclass.EmcPose.getDefaultInstance();
      }

      public pb.Emcclass.EmcPose build() {
        pb.Emcclass.EmcPose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Emcclass.EmcPose buildPartial() {
        pb.Emcclass.EmcPose result = new pb.Emcclass.EmcPose(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (tranBuilder_ == null) {
          result.tran_ = tran_;
        } else {
          result.tran_ = tranBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.a_ = a_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.b_ = b_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.c_ = c_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.u_ = u_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.v_ = v_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.w_ = w_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Emcclass.EmcPose) {
          return mergeFrom((pb.Emcclass.EmcPose)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Emcclass.EmcPose other) {
        if (other == pb.Emcclass.EmcPose.getDefaultInstance()) return this;
        if (other.hasTran()) {
          mergeTran(other.getTran());
        }
        if (other.hasA()) {
          setA(other.getA());
        }
        if (other.hasB()) {
          setB(other.getB());
        }
        if (other.hasC()) {
          setC(other.getC());
        }
        if (other.hasU()) {
          setU(other.getU());
        }
        if (other.hasV()) {
          setV(other.getV());
        }
        if (other.hasW()) {
          setW(other.getW());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTran()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Emcclass.EmcPose parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Emcclass.EmcPose) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private pb.Emcclass.PmCartesian tran_ = pb.Emcclass.PmCartesian.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pb.Emcclass.PmCartesian, pb.Emcclass.PmCartesian.Builder, pb.Emcclass.PmCartesianOrBuilder> tranBuilder_;
      /**
       * <code>required .pb.PmCartesian tran = 10;</code>
       */
      public boolean hasTran() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .pb.PmCartesian tran = 10;</code>
       */
      public pb.Emcclass.PmCartesian getTran() {
        if (tranBuilder_ == null) {
          return tran_;
        } else {
          return tranBuilder_.getMessage();
        }
      }
      /**
       * <code>required .pb.PmCartesian tran = 10;</code>
       */
      public Builder setTran(pb.Emcclass.PmCartesian value) {
        if (tranBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tran_ = value;
          onChanged();
        } else {
          tranBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .pb.PmCartesian tran = 10;</code>
       */
      public Builder setTran(
          pb.Emcclass.PmCartesian.Builder builderForValue) {
        if (tranBuilder_ == null) {
          tran_ = builderForValue.build();
          onChanged();
        } else {
          tranBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .pb.PmCartesian tran = 10;</code>
       */
      public Builder mergeTran(pb.Emcclass.PmCartesian value) {
        if (tranBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              tran_ != pb.Emcclass.PmCartesian.getDefaultInstance()) {
            tran_ =
              pb.Emcclass.PmCartesian.newBuilder(tran_).mergeFrom(value).buildPartial();
          } else {
            tran_ = value;
          }
          onChanged();
        } else {
          tranBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .pb.PmCartesian tran = 10;</code>
       */
      public Builder clearTran() {
        if (tranBuilder_ == null) {
          tran_ = pb.Emcclass.PmCartesian.getDefaultInstance();
          onChanged();
        } else {
          tranBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .pb.PmCartesian tran = 10;</code>
       */
      public pb.Emcclass.PmCartesian.Builder getTranBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTranFieldBuilder().getBuilder();
      }
      /**
       * <code>required .pb.PmCartesian tran = 10;</code>
       */
      public pb.Emcclass.PmCartesianOrBuilder getTranOrBuilder() {
        if (tranBuilder_ != null) {
          return tranBuilder_.getMessageOrBuilder();
        } else {
          return tran_;
        }
      }
      /**
       * <code>required .pb.PmCartesian tran = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pb.Emcclass.PmCartesian, pb.Emcclass.PmCartesian.Builder, pb.Emcclass.PmCartesianOrBuilder> 
          getTranFieldBuilder() {
        if (tranBuilder_ == null) {
          tranBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pb.Emcclass.PmCartesian, pb.Emcclass.PmCartesian.Builder, pb.Emcclass.PmCartesianOrBuilder>(
                  getTran(),
                  getParentForChildren(),
                  isClean());
          tran_ = null;
        }
        return tranBuilder_;
      }

      private double a_ ;
      /**
       * <code>optional double a = 20;</code>
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double a = 20;</code>
       */
      public double getA() {
        return a_;
      }
      /**
       * <code>optional double a = 20;</code>
       */
      public Builder setA(double value) {
        bitField0_ |= 0x00000002;
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double a = 20;</code>
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000002);
        a_ = 0D;
        onChanged();
        return this;
      }

      private double b_ ;
      /**
       * <code>optional double b = 30;</code>
       */
      public boolean hasB() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double b = 30;</code>
       */
      public double getB() {
        return b_;
      }
      /**
       * <code>optional double b = 30;</code>
       */
      public Builder setB(double value) {
        bitField0_ |= 0x00000004;
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double b = 30;</code>
       */
      public Builder clearB() {
        bitField0_ = (bitField0_ & ~0x00000004);
        b_ = 0D;
        onChanged();
        return this;
      }

      private double c_ ;
      /**
       * <code>optional double c = 40;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double c = 40;</code>
       */
      public double getC() {
        return c_;
      }
      /**
       * <code>optional double c = 40;</code>
       */
      public Builder setC(double value) {
        bitField0_ |= 0x00000008;
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double c = 40;</code>
       */
      public Builder clearC() {
        bitField0_ = (bitField0_ & ~0x00000008);
        c_ = 0D;
        onChanged();
        return this;
      }

      private double u_ ;
      /**
       * <code>optional double u = 50;</code>
       */
      public boolean hasU() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double u = 50;</code>
       */
      public double getU() {
        return u_;
      }
      /**
       * <code>optional double u = 50;</code>
       */
      public Builder setU(double value) {
        bitField0_ |= 0x00000010;
        u_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double u = 50;</code>
       */
      public Builder clearU() {
        bitField0_ = (bitField0_ & ~0x00000010);
        u_ = 0D;
        onChanged();
        return this;
      }

      private double v_ ;
      /**
       * <code>optional double v = 60;</code>
       */
      public boolean hasV() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double v = 60;</code>
       */
      public double getV() {
        return v_;
      }
      /**
       * <code>optional double v = 60;</code>
       */
      public Builder setV(double value) {
        bitField0_ |= 0x00000020;
        v_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double v = 60;</code>
       */
      public Builder clearV() {
        bitField0_ = (bitField0_ & ~0x00000020);
        v_ = 0D;
        onChanged();
        return this;
      }

      private double w_ ;
      /**
       * <code>optional double w = 70;</code>
       */
      public boolean hasW() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double w = 70;</code>
       */
      public double getW() {
        return w_;
      }
      /**
       * <code>optional double w = 70;</code>
       */
      public Builder setW(double value) {
        bitField0_ |= 0x00000040;
        w_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double w = 70;</code>
       */
      public Builder clearW() {
        bitField0_ = (bitField0_ & ~0x00000040);
        w_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.EmcPose)
    }

    static {
      defaultInstance = new EmcPose(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.EmcPose)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PmCartesian_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_PmCartesian_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_EmcPose_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_EmcPose_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#machinetalk/protobuf/emcclass.proto\022\002p" +
      "b\032!machinetalk/protobuf/nanopb.proto\"6\n\013" +
      "PmCartesian\022\t\n\001x\030\n \001(\001\022\t\n\001y\030\024 \001(\001\022\t\n\001z\030\036" +
      " \001(\001:\006\222?\003H\254\002\"r\n\007EmcPose\022\035\n\004tran\030\n \002(\0132\017." +
      "pb.PmCartesian\022\t\n\001a\030\024 \001(\001\022\t\n\001b\030\036 \001(\001\022\t\n\001" +
      "c\030( \001(\001\022\t\n\001u\0302 \001(\001\022\t\n\001v\030< \001(\001\022\t\n\001w\030F \001(\001" +
      ":\006\222?\003H\255\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor(),
        }, assigner);
    internal_static_pb_PmCartesian_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_PmCartesian_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_PmCartesian_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_pb_EmcPose_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_EmcPose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_EmcPose_descriptor,
        new java.lang.String[] { "Tran", "A", "B", "C", "U", "V", "W", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
