// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: machinetalk/protobuf/log.proto

package pb;

public final class Log {
  private Log() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.LogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .pb.MsgOrigin origin = 10;</code>
     */
    boolean hasOrigin();
    /**
     * <code>required .pb.MsgOrigin origin = 10;</code>
     */
    pb.Types.MsgOrigin getOrigin();

    /**
     * <code>required int32 pid = 20;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 20;</code>
     */
    int getPid();

    /**
     * <code>required .pb.MsgLevel level = 30;</code>
     */
    boolean hasLevel();
    /**
     * <code>required .pb.MsgLevel level = 30;</code>
     */
    pb.Types.MsgLevel getLevel();

    /**
     * <code>required string tag = 40;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 20];
     * </pre>
     */
    boolean hasTag();
    /**
     * <code>required string tag = 40;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 20];
     * </pre>
     */
    java.lang.String getTag();
    /**
     * <code>required string tag = 40;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 20];
     * </pre>
     */
    com.google.protobuf.ByteString
        getTagBytes();

    /**
     * <code>required string text = 50;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 100];
     * </pre>
     */
    boolean hasText();
    /**
     * <code>required string text = 50;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 100];
     * </pre>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 50;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 100];
     * </pre>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code pb.LogMessage}
   */
  public static final class LogMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.LogMessage)
      LogMessageOrBuilder {
    // Use LogMessage.newBuilder() to construct.
    private LogMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogMessage defaultInstance;
    public static LogMessage getDefaultInstance() {
      return defaultInstance;
    }

    public LogMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 80: {
              int rawValue = input.readEnum();
              pb.Types.MsgOrigin value = pb.Types.MsgOrigin.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(10, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                origin_ = value;
              }
              break;
            }
            case 160: {
              bitField0_ |= 0x00000002;
              pid_ = input.readInt32();
              break;
            }
            case 240: {
              int rawValue = input.readEnum();
              pb.Types.MsgLevel value = pb.Types.MsgLevel.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(30, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                level_ = value;
              }
              break;
            }
            case 322: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              tag_ = bs;
              break;
            }
            case 402: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              text_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Log.internal_static_pb_LogMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Log.internal_static_pb_LogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Log.LogMessage.class, pb.Log.LogMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<LogMessage> PARSER =
        new com.google.protobuf.AbstractParser<LogMessage>() {
      public LogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ORIGIN_FIELD_NUMBER = 10;
    private pb.Types.MsgOrigin origin_;
    /**
     * <code>required .pb.MsgOrigin origin = 10;</code>
     */
    public boolean hasOrigin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .pb.MsgOrigin origin = 10;</code>
     */
    public pb.Types.MsgOrigin getOrigin() {
      return origin_;
    }

    public static final int PID_FIELD_NUMBER = 20;
    private int pid_;
    /**
     * <code>required int32 pid = 20;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 pid = 20;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int LEVEL_FIELD_NUMBER = 30;
    private pb.Types.MsgLevel level_;
    /**
     * <code>required .pb.MsgLevel level = 30;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .pb.MsgLevel level = 30;</code>
     */
    public pb.Types.MsgLevel getLevel() {
      return level_;
    }

    public static final int TAG_FIELD_NUMBER = 40;
    private java.lang.Object tag_;
    /**
     * <code>required string tag = 40;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 20];
     * </pre>
     */
    public boolean hasTag() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string tag = 40;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 20];
     * </pre>
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tag_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tag = 40;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 20];
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXT_FIELD_NUMBER = 50;
    private java.lang.Object text_;
    /**
     * <code>required string text = 50;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 100];
     * </pre>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string text = 50;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 100];
     * </pre>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 50;</code>
     *
     * <pre>
     *  [(nanopb).max_size = 100];
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      origin_ = pb.Types.MsgOrigin.MSG_KERNEL;
      pid_ = 0;
      level_ = pb.Types.MsgLevel.RTAPI_MSG_NONE;
      tag_ = "";
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOrigin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(10, origin_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(20, pid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(30, level_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(40, getTagBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(50, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, origin_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, pid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(30, level_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(40, getTagBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(50, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pb.Log.LogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Log.LogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Log.LogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Log.LogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Log.LogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Log.LogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pb.Log.LogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pb.Log.LogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pb.Log.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Log.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pb.Log.LogMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.LogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.LogMessage)
        pb.Log.LogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Log.internal_static_pb_LogMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Log.internal_static_pb_LogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Log.LogMessage.class, pb.Log.LogMessage.Builder.class);
      }

      // Construct using pb.Log.LogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        origin_ = pb.Types.MsgOrigin.MSG_KERNEL;
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = pb.Types.MsgLevel.RTAPI_MSG_NONE;
        bitField0_ = (bitField0_ & ~0x00000004);
        tag_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Log.internal_static_pb_LogMessage_descriptor;
      }

      public pb.Log.LogMessage getDefaultInstanceForType() {
        return pb.Log.LogMessage.getDefaultInstance();
      }

      public pb.Log.LogMessage build() {
        pb.Log.LogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Log.LogMessage buildPartial() {
        pb.Log.LogMessage result = new pb.Log.LogMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.origin_ = origin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.tag_ = tag_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Log.LogMessage) {
          return mergeFrom((pb.Log.LogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Log.LogMessage other) {
        if (other == pb.Log.LogMessage.getDefaultInstance()) return this;
        if (other.hasOrigin()) {
          setOrigin(other.getOrigin());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasTag()) {
          bitField0_ |= 0x00000008;
          tag_ = other.tag_;
          onChanged();
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000010;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrigin()) {
          
          return false;
        }
        if (!hasPid()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasTag()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Log.LogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Log.LogMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private pb.Types.MsgOrigin origin_ = pb.Types.MsgOrigin.MSG_KERNEL;
      /**
       * <code>required .pb.MsgOrigin origin = 10;</code>
       */
      public boolean hasOrigin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .pb.MsgOrigin origin = 10;</code>
       */
      public pb.Types.MsgOrigin getOrigin() {
        return origin_;
      }
      /**
       * <code>required .pb.MsgOrigin origin = 10;</code>
       */
      public Builder setOrigin(pb.Types.MsgOrigin value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        origin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .pb.MsgOrigin origin = 10;</code>
       */
      public Builder clearOrigin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        origin_ = pb.Types.MsgOrigin.MSG_KERNEL;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required int32 pid = 20;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 pid = 20;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 20;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000002;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 20;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        onChanged();
        return this;
      }

      private pb.Types.MsgLevel level_ = pb.Types.MsgLevel.RTAPI_MSG_NONE;
      /**
       * <code>required .pb.MsgLevel level = 30;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .pb.MsgLevel level = 30;</code>
       */
      public pb.Types.MsgLevel getLevel() {
        return level_;
      }
      /**
       * <code>required .pb.MsgLevel level = 30;</code>
       */
      public Builder setLevel(pb.Types.MsgLevel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .pb.MsgLevel level = 30;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = pb.Types.MsgLevel.RTAPI_MSG_NONE;
        onChanged();
        return this;
      }

      private java.lang.Object tag_ = "";
      /**
       * <code>required string tag = 40;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 20];
       * </pre>
       */
      public boolean hasTag() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string tag = 40;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 20];
       * </pre>
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tag_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tag = 40;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 20];
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tag = 40;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 20];
       * </pre>
       */
      public Builder setTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tag = 40;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 20];
       * </pre>
       */
      public Builder clearTag() {
        bitField0_ = (bitField0_ & ~0x00000008);
        tag_ = getDefaultInstance().getTag();
        onChanged();
        return this;
      }
      /**
       * <code>required string tag = 40;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 20];
       * </pre>
       */
      public Builder setTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        tag_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 50;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 100];
       * </pre>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string text = 50;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 100];
       * </pre>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 50;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 100];
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 50;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 100];
       * </pre>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 50;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 100];
       * </pre>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000010);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 50;</code>
       *
       * <pre>
       *  [(nanopb).max_size = 100];
       * </pre>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.LogMessage)
    }

    static {
      defaultInstance = new LogMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.LogMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_LogMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_LogMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036machinetalk/protobuf/log.proto\022\002pb\032!ma" +
      "chinetalk/protobuf/nanopb.proto\032 machine" +
      "talk/protobuf/types.proto\"x\n\nLogMessage\022" +
      "\035\n\006origin\030\n \002(\0162\r.pb.MsgOrigin\022\013\n\003pid\030\024 " +
      "\002(\005\022\033\n\005level\030\036 \002(\0162\014.pb.MsgLevel\022\013\n\003tag\030" +
      "( \002(\t\022\014\n\004text\0302 \002(\t:\006\222?\003H\220\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor(),
          pb.Types.getDescriptor(),
        }, assigner);
    internal_static_pb_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_LogMessage_descriptor,
        new java.lang.String[] { "Origin", "Pid", "Level", "Tag", "Text", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor();
    pb.Types.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
