// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: machinetalk/protobuf/rtapi_message.proto

package pb;

public final class RtapiMessage {
  private RtapiMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RTAPI_MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.RTAPI_Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 msglevel = 10;</code>
     *
     * <pre>
     * [default = RTAPI_MSG_DBG];
     * </pre>
     */
    boolean hasMsglevel();
    /**
     * <code>required int32 msglevel = 10;</code>
     *
     * <pre>
     * [default = RTAPI_MSG_DBG];
     * </pre>
     */
    int getMsglevel();

    /**
     * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
     */
    boolean hasFormat();
    /**
     * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
     */
    java.lang.String getFormat();
    /**
     * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
     */
    com.google.protobuf.ByteString
        getFormatBytes();

    /**
     * <code>repeated .pb.Value arg = 30;</code>
     *
     * <pre>
     * if this list of scalars is non-empty,
     * this implies sprintf(text, &lt;arg&gt;) should be applied
     * before display
     * </pre>
     */
    java.util.List<pb.ValueOuterClass.Value> 
        getArgList();
    /**
     * <code>repeated .pb.Value arg = 30;</code>
     *
     * <pre>
     * if this list of scalars is non-empty,
     * this implies sprintf(text, &lt;arg&gt;) should be applied
     * before display
     * </pre>
     */
    pb.ValueOuterClass.Value getArg(int index);
    /**
     * <code>repeated .pb.Value arg = 30;</code>
     *
     * <pre>
     * if this list of scalars is non-empty,
     * this implies sprintf(text, &lt;arg&gt;) should be applied
     * before display
     * </pre>
     */
    int getArgCount();
    /**
     * <code>repeated .pb.Value arg = 30;</code>
     *
     * <pre>
     * if this list of scalars is non-empty,
     * this implies sprintf(text, &lt;arg&gt;) should be applied
     * before display
     * </pre>
     */
    java.util.List<? extends pb.ValueOuterClass.ValueOrBuilder> 
        getArgOrBuilderList();
    /**
     * <code>repeated .pb.Value arg = 30;</code>
     *
     * <pre>
     * if this list of scalars is non-empty,
     * this implies sprintf(text, &lt;arg&gt;) should be applied
     * before display
     * </pre>
     */
    pb.ValueOuterClass.ValueOrBuilder getArgOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pb.RTAPI_Message}
   */
  public static final class RTAPI_Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.RTAPI_Message)
      RTAPI_MessageOrBuilder {
    // Use RTAPI_Message.newBuilder() to construct.
    private RTAPI_Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RTAPI_Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RTAPI_Message defaultInstance;
    public static RTAPI_Message getDefaultInstance() {
      return defaultInstance;
    }

    public RTAPI_Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RTAPI_Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 80: {
              bitField0_ |= 0x00000001;
              msglevel_ = input.readInt32();
              break;
            }
            case 162: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              format_ = bs;
              break;
            }
            case 242: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                arg_ = new java.util.ArrayList<pb.ValueOuterClass.Value>();
                mutable_bitField0_ |= 0x00000004;
              }
              arg_.add(input.readMessage(pb.ValueOuterClass.Value.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          arg_ = java.util.Collections.unmodifiableList(arg_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.RtapiMessage.internal_static_pb_RTAPI_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.RtapiMessage.internal_static_pb_RTAPI_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.RtapiMessage.RTAPI_Message.class, pb.RtapiMessage.RTAPI_Message.Builder.class);
    }

    public static com.google.protobuf.Parser<RTAPI_Message> PARSER =
        new com.google.protobuf.AbstractParser<RTAPI_Message>() {
      public RTAPI_Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RTAPI_Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RTAPI_Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSGLEVEL_FIELD_NUMBER = 10;
    private int msglevel_;
    /**
     * <code>required int32 msglevel = 10;</code>
     *
     * <pre>
     * [default = RTAPI_MSG_DBG];
     * </pre>
     */
    public boolean hasMsglevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msglevel = 10;</code>
     *
     * <pre>
     * [default = RTAPI_MSG_DBG];
     * </pre>
     */
    public int getMsglevel() {
      return msglevel_;
    }

    public static final int FORMAT_FIELD_NUMBER = 20;
    private java.lang.Object format_;
    /**
     * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
     */
    public boolean hasFormat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
     */
    public java.lang.String getFormat() {
      java.lang.Object ref = format_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          format_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
     */
    public com.google.protobuf.ByteString
        getFormatBytes() {
      java.lang.Object ref = format_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARG_FIELD_NUMBER = 30;
    private java.util.List<pb.ValueOuterClass.Value> arg_;
    /**
     * <code>repeated .pb.Value arg = 30;</code>
     *
     * <pre>
     * if this list of scalars is non-empty,
     * this implies sprintf(text, &lt;arg&gt;) should be applied
     * before display
     * </pre>
     */
    public java.util.List<pb.ValueOuterClass.Value> getArgList() {
      return arg_;
    }
    /**
     * <code>repeated .pb.Value arg = 30;</code>
     *
     * <pre>
     * if this list of scalars is non-empty,
     * this implies sprintf(text, &lt;arg&gt;) should be applied
     * before display
     * </pre>
     */
    public java.util.List<? extends pb.ValueOuterClass.ValueOrBuilder> 
        getArgOrBuilderList() {
      return arg_;
    }
    /**
     * <code>repeated .pb.Value arg = 30;</code>
     *
     * <pre>
     * if this list of scalars is non-empty,
     * this implies sprintf(text, &lt;arg&gt;) should be applied
     * before display
     * </pre>
     */
    public int getArgCount() {
      return arg_.size();
    }
    /**
     * <code>repeated .pb.Value arg = 30;</code>
     *
     * <pre>
     * if this list of scalars is non-empty,
     * this implies sprintf(text, &lt;arg&gt;) should be applied
     * before display
     * </pre>
     */
    public pb.ValueOuterClass.Value getArg(int index) {
      return arg_.get(index);
    }
    /**
     * <code>repeated .pb.Value arg = 30;</code>
     *
     * <pre>
     * if this list of scalars is non-empty,
     * this implies sprintf(text, &lt;arg&gt;) should be applied
     * before display
     * </pre>
     */
    public pb.ValueOuterClass.ValueOrBuilder getArgOrBuilder(
        int index) {
      return arg_.get(index);
    }

    private void initFields() {
      msglevel_ = 0;
      format_ = "*** uninitialized ***";
      arg_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsglevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFormat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getArgCount(); i++) {
        if (!getArg(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(10, msglevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(20, getFormatBytes());
      }
      for (int i = 0; i < arg_.size(); i++) {
        output.writeMessage(30, arg_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, msglevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, getFormatBytes());
      }
      for (int i = 0; i < arg_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(30, arg_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pb.RtapiMessage.RTAPI_Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.RtapiMessage.RTAPI_Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.RtapiMessage.RTAPI_Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.RtapiMessage.RTAPI_Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.RtapiMessage.RTAPI_Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.RtapiMessage.RTAPI_Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pb.RtapiMessage.RTAPI_Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pb.RtapiMessage.RTAPI_Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pb.RtapiMessage.RTAPI_Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.RtapiMessage.RTAPI_Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pb.RtapiMessage.RTAPI_Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.RTAPI_Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.RTAPI_Message)
        pb.RtapiMessage.RTAPI_MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.RtapiMessage.internal_static_pb_RTAPI_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.RtapiMessage.internal_static_pb_RTAPI_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.RtapiMessage.RTAPI_Message.class, pb.RtapiMessage.RTAPI_Message.Builder.class);
      }

      // Construct using pb.RtapiMessage.RTAPI_Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getArgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msglevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        format_ = "*** uninitialized ***";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (argBuilder_ == null) {
          arg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          argBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.RtapiMessage.internal_static_pb_RTAPI_Message_descriptor;
      }

      public pb.RtapiMessage.RTAPI_Message getDefaultInstanceForType() {
        return pb.RtapiMessage.RTAPI_Message.getDefaultInstance();
      }

      public pb.RtapiMessage.RTAPI_Message build() {
        pb.RtapiMessage.RTAPI_Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.RtapiMessage.RTAPI_Message buildPartial() {
        pb.RtapiMessage.RTAPI_Message result = new pb.RtapiMessage.RTAPI_Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msglevel_ = msglevel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.format_ = format_;
        if (argBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            arg_ = java.util.Collections.unmodifiableList(arg_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.arg_ = arg_;
        } else {
          result.arg_ = argBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.RtapiMessage.RTAPI_Message) {
          return mergeFrom((pb.RtapiMessage.RTAPI_Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.RtapiMessage.RTAPI_Message other) {
        if (other == pb.RtapiMessage.RTAPI_Message.getDefaultInstance()) return this;
        if (other.hasMsglevel()) {
          setMsglevel(other.getMsglevel());
        }
        if (other.hasFormat()) {
          bitField0_ |= 0x00000002;
          format_ = other.format_;
          onChanged();
        }
        if (argBuilder_ == null) {
          if (!other.arg_.isEmpty()) {
            if (arg_.isEmpty()) {
              arg_ = other.arg_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureArgIsMutable();
              arg_.addAll(other.arg_);
            }
            onChanged();
          }
        } else {
          if (!other.arg_.isEmpty()) {
            if (argBuilder_.isEmpty()) {
              argBuilder_.dispose();
              argBuilder_ = null;
              arg_ = other.arg_;
              bitField0_ = (bitField0_ & ~0x00000004);
              argBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getArgFieldBuilder() : null;
            } else {
              argBuilder_.addAllMessages(other.arg_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsglevel()) {
          
          return false;
        }
        if (!hasFormat()) {
          
          return false;
        }
        for (int i = 0; i < getArgCount(); i++) {
          if (!getArg(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.RtapiMessage.RTAPI_Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.RtapiMessage.RTAPI_Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msglevel_ ;
      /**
       * <code>required int32 msglevel = 10;</code>
       *
       * <pre>
       * [default = RTAPI_MSG_DBG];
       * </pre>
       */
      public boolean hasMsglevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 msglevel = 10;</code>
       *
       * <pre>
       * [default = RTAPI_MSG_DBG];
       * </pre>
       */
      public int getMsglevel() {
        return msglevel_;
      }
      /**
       * <code>required int32 msglevel = 10;</code>
       *
       * <pre>
       * [default = RTAPI_MSG_DBG];
       * </pre>
       */
      public Builder setMsglevel(int value) {
        bitField0_ |= 0x00000001;
        msglevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msglevel = 10;</code>
       *
       * <pre>
       * [default = RTAPI_MSG_DBG];
       * </pre>
       */
      public Builder clearMsglevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msglevel_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object format_ = "*** uninitialized ***";
      /**
       * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
       */
      public boolean hasFormat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
       */
      public java.lang.String getFormat() {
        java.lang.Object ref = format_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            format_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
       */
      public com.google.protobuf.ByteString
          getFormatBytes() {
        java.lang.Object ref = format_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          format_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
       */
      public Builder setFormat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        format_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
       */
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        format_ = getDefaultInstance().getFormat();
        onChanged();
        return this;
      }
      /**
       * <code>required string format = 20 [default = "*** uninitialized ***"];</code>
       */
      public Builder setFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        format_ = value;
        onChanged();
        return this;
      }

      private java.util.List<pb.ValueOuterClass.Value> arg_ =
        java.util.Collections.emptyList();
      private void ensureArgIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          arg_ = new java.util.ArrayList<pb.ValueOuterClass.Value>(arg_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          pb.ValueOuterClass.Value, pb.ValueOuterClass.Value.Builder, pb.ValueOuterClass.ValueOrBuilder> argBuilder_;

      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public java.util.List<pb.ValueOuterClass.Value> getArgList() {
        if (argBuilder_ == null) {
          return java.util.Collections.unmodifiableList(arg_);
        } else {
          return argBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public int getArgCount() {
        if (argBuilder_ == null) {
          return arg_.size();
        } else {
          return argBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public pb.ValueOuterClass.Value getArg(int index) {
        if (argBuilder_ == null) {
          return arg_.get(index);
        } else {
          return argBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public Builder setArg(
          int index, pb.ValueOuterClass.Value value) {
        if (argBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgIsMutable();
          arg_.set(index, value);
          onChanged();
        } else {
          argBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public Builder setArg(
          int index, pb.ValueOuterClass.Value.Builder builderForValue) {
        if (argBuilder_ == null) {
          ensureArgIsMutable();
          arg_.set(index, builderForValue.build());
          onChanged();
        } else {
          argBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public Builder addArg(pb.ValueOuterClass.Value value) {
        if (argBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgIsMutable();
          arg_.add(value);
          onChanged();
        } else {
          argBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public Builder addArg(
          int index, pb.ValueOuterClass.Value value) {
        if (argBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgIsMutable();
          arg_.add(index, value);
          onChanged();
        } else {
          argBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public Builder addArg(
          pb.ValueOuterClass.Value.Builder builderForValue) {
        if (argBuilder_ == null) {
          ensureArgIsMutable();
          arg_.add(builderForValue.build());
          onChanged();
        } else {
          argBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public Builder addArg(
          int index, pb.ValueOuterClass.Value.Builder builderForValue) {
        if (argBuilder_ == null) {
          ensureArgIsMutable();
          arg_.add(index, builderForValue.build());
          onChanged();
        } else {
          argBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public Builder addAllArg(
          java.lang.Iterable<? extends pb.ValueOuterClass.Value> values) {
        if (argBuilder_ == null) {
          ensureArgIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, arg_);
          onChanged();
        } else {
          argBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public Builder clearArg() {
        if (argBuilder_ == null) {
          arg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          argBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public Builder removeArg(int index) {
        if (argBuilder_ == null) {
          ensureArgIsMutable();
          arg_.remove(index);
          onChanged();
        } else {
          argBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public pb.ValueOuterClass.Value.Builder getArgBuilder(
          int index) {
        return getArgFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public pb.ValueOuterClass.ValueOrBuilder getArgOrBuilder(
          int index) {
        if (argBuilder_ == null) {
          return arg_.get(index);  } else {
          return argBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public java.util.List<? extends pb.ValueOuterClass.ValueOrBuilder> 
           getArgOrBuilderList() {
        if (argBuilder_ != null) {
          return argBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(arg_);
        }
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public pb.ValueOuterClass.Value.Builder addArgBuilder() {
        return getArgFieldBuilder().addBuilder(
            pb.ValueOuterClass.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public pb.ValueOuterClass.Value.Builder addArgBuilder(
          int index) {
        return getArgFieldBuilder().addBuilder(
            index, pb.ValueOuterClass.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .pb.Value arg = 30;</code>
       *
       * <pre>
       * if this list of scalars is non-empty,
       * this implies sprintf(text, &lt;arg&gt;) should be applied
       * before display
       * </pre>
       */
      public java.util.List<pb.ValueOuterClass.Value.Builder> 
           getArgBuilderList() {
        return getArgFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pb.ValueOuterClass.Value, pb.ValueOuterClass.Value.Builder, pb.ValueOuterClass.ValueOrBuilder> 
          getArgFieldBuilder() {
        if (argBuilder_ == null) {
          argBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pb.ValueOuterClass.Value, pb.ValueOuterClass.Value.Builder, pb.ValueOuterClass.ValueOrBuilder>(
                  arg_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          arg_ = null;
        }
        return argBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pb.RTAPI_Message)
    }

    static {
      defaultInstance = new RTAPI_Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.RTAPI_Message)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_RTAPI_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_RTAPI_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(machinetalk/protobuf/rtapi_message.pro" +
      "to\022\002pb\032!machinetalk/protobuf/nanopb.prot" +
      "o\032 machinetalk/protobuf/value.proto\"v\n\rR" +
      "TAPI_Message\022\020\n\010msglevel\030\n \002(\005\022,\n\006format" +
      "\030\024 \002(\t:\025*** uninitialized ***B\005\222?\002\010d\022\035\n\003" +
      "arg\030\036 \003(\0132\t.pb.ValueB\005\222?\002\020\n:\006\222?\003H\350\007"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor(),
          pb.ValueOuterClass.getDescriptor(),
        }, assigner);
    internal_static_pb_RTAPI_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_RTAPI_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_RTAPI_Message_descriptor,
        new java.lang.String[] { "Msglevel", "Format", "Arg", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopb);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopb);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor();
    pb.ValueOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
