// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: machinetalk/protobuf/rtapicommand.proto

package pb;

public final class Rtapicommand {
  private Rtapicommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RTAPICommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.RTAPICommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 instance = 1;</code>
     */
    boolean hasInstance();
    /**
     * <code>required int32 instance = 1;</code>
     */
    int getInstance();

    /**
     * <code>optional string modname = 2;</code>
     */
    boolean hasModname();
    /**
     * <code>optional string modname = 2;</code>
     */
    java.lang.String getModname();
    /**
     * <code>optional string modname = 2;</code>
     */
    com.google.protobuf.ByteString
        getModnameBytes();

    /**
     * <code>optional int32 rt_msglevel = 3;</code>
     */
    boolean hasRtMsglevel();
    /**
     * <code>optional int32 rt_msglevel = 3;</code>
     */
    int getRtMsglevel();

    /**
     * <code>optional int32 user_msglevel = 4;</code>
     */
    boolean hasUserMsglevel();
    /**
     * <code>optional int32 user_msglevel = 4;</code>
     */
    int getUserMsglevel();

    /**
     * <code>repeated string argv = 5;</code>
     *
     * <pre>
     * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getArgvList();
    /**
     * <code>repeated string argv = 5;</code>
     *
     * <pre>
     * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
     * </pre>
     */
    int getArgvCount();
    /**
     * <code>repeated string argv = 5;</code>
     *
     * <pre>
     * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
     * </pre>
     */
    java.lang.String getArgv(int index);
    /**
     * <code>repeated string argv = 5;</code>
     *
     * <pre>
     * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
     * </pre>
     */
    com.google.protobuf.ByteString
        getArgvBytes(int index);

    /**
     * <code>optional string threadname = 6;</code>
     */
    boolean hasThreadname();
    /**
     * <code>optional string threadname = 6;</code>
     */
    java.lang.String getThreadname();
    /**
     * <code>optional string threadname = 6;</code>
     */
    com.google.protobuf.ByteString
        getThreadnameBytes();

    /**
     * <code>optional int32 threadperiod = 7;</code>
     */
    boolean hasThreadperiod();
    /**
     * <code>optional int32 threadperiod = 7;</code>
     */
    int getThreadperiod();

    /**
     * <code>optional bool use_fp = 8;</code>
     */
    boolean hasUseFp();
    /**
     * <code>optional bool use_fp = 8;</code>
     */
    boolean getUseFp();

    /**
     * <code>optional int32 cpu = 9;</code>
     */
    boolean hasCpu();
    /**
     * <code>optional int32 cpu = 9;</code>
     */
    int getCpu();

    /**
     * <code>optional string comp = 10;</code>
     */
    boolean hasComp();
    /**
     * <code>optional string comp = 10;</code>
     */
    java.lang.String getComp();
    /**
     * <code>optional string comp = 10;</code>
     */
    com.google.protobuf.ByteString
        getCompBytes();

    /**
     * <code>optional string func = 11;</code>
     */
    boolean hasFunc();
    /**
     * <code>optional string func = 11;</code>
     */
    java.lang.String getFunc();
    /**
     * <code>optional string func = 11;</code>
     */
    com.google.protobuf.ByteString
        getFuncBytes();

    /**
     * <code>optional string instname = 12;</code>
     */
    boolean hasInstname();
    /**
     * <code>optional string instname = 12;</code>
     */
    java.lang.String getInstname();
    /**
     * <code>optional string instname = 12;</code>
     */
    com.google.protobuf.ByteString
        getInstnameBytes();

    /**
     * <code>optional int32 flags = 13;</code>
     */
    boolean hasFlags();
    /**
     * <code>optional int32 flags = 13;</code>
     */
    int getFlags();
  }
  /**
   * Protobuf type {@code pb.RTAPICommand}
   */
  public static final class RTAPICommand extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.RTAPICommand)
      RTAPICommandOrBuilder {
    // Use RTAPICommand.newBuilder() to construct.
    private RTAPICommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RTAPICommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RTAPICommand defaultInstance;
    public static RTAPICommand getDefaultInstance() {
      return defaultInstance;
    }

    public RTAPICommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RTAPICommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              instance_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              modname_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rtMsglevel_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              userMsglevel_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                argv_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              argv_.add(bs);
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              threadname_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              threadperiod_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              useFp_ = input.readBool();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              cpu_ = input.readInt32();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              comp_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              func_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              instname_ = bs;
              break;
            }
            case 104: {
              bitField0_ |= 0x00000800;
              flags_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          argv_ = argv_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Rtapicommand.internal_static_pb_RTAPICommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Rtapicommand.internal_static_pb_RTAPICommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Rtapicommand.RTAPICommand.class, pb.Rtapicommand.RTAPICommand.Builder.class);
    }

    public static com.google.protobuf.Parser<RTAPICommand> PARSER =
        new com.google.protobuf.AbstractParser<RTAPICommand>() {
      public RTAPICommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RTAPICommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RTAPICommand> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INSTANCE_FIELD_NUMBER = 1;
    private int instance_;
    /**
     * <code>required int32 instance = 1;</code>
     */
    public boolean hasInstance() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 instance = 1;</code>
     */
    public int getInstance() {
      return instance_;
    }

    public static final int MODNAME_FIELD_NUMBER = 2;
    private java.lang.Object modname_;
    /**
     * <code>optional string modname = 2;</code>
     */
    public boolean hasModname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string modname = 2;</code>
     */
    public java.lang.String getModname() {
      java.lang.Object ref = modname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          modname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string modname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getModnameBytes() {
      java.lang.Object ref = modname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RT_MSGLEVEL_FIELD_NUMBER = 3;
    private int rtMsglevel_;
    /**
     * <code>optional int32 rt_msglevel = 3;</code>
     */
    public boolean hasRtMsglevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 rt_msglevel = 3;</code>
     */
    public int getRtMsglevel() {
      return rtMsglevel_;
    }

    public static final int USER_MSGLEVEL_FIELD_NUMBER = 4;
    private int userMsglevel_;
    /**
     * <code>optional int32 user_msglevel = 4;</code>
     */
    public boolean hasUserMsglevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 user_msglevel = 4;</code>
     */
    public int getUserMsglevel() {
      return userMsglevel_;
    }

    public static final int ARGV_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList argv_;
    /**
     * <code>repeated string argv = 5;</code>
     *
     * <pre>
     * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getArgvList() {
      return argv_;
    }
    /**
     * <code>repeated string argv = 5;</code>
     *
     * <pre>
     * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
     * </pre>
     */
    public int getArgvCount() {
      return argv_.size();
    }
    /**
     * <code>repeated string argv = 5;</code>
     *
     * <pre>
     * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
     * </pre>
     */
    public java.lang.String getArgv(int index) {
      return argv_.get(index);
    }
    /**
     * <code>repeated string argv = 5;</code>
     *
     * <pre>
     * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
     * </pre>
     */
    public com.google.protobuf.ByteString
        getArgvBytes(int index) {
      return argv_.getByteString(index);
    }

    public static final int THREADNAME_FIELD_NUMBER = 6;
    private java.lang.Object threadname_;
    /**
     * <code>optional string threadname = 6;</code>
     */
    public boolean hasThreadname() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string threadname = 6;</code>
     */
    public java.lang.String getThreadname() {
      java.lang.Object ref = threadname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          threadname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string threadname = 6;</code>
     */
    public com.google.protobuf.ByteString
        getThreadnameBytes() {
      java.lang.Object ref = threadname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        threadname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THREADPERIOD_FIELD_NUMBER = 7;
    private int threadperiod_;
    /**
     * <code>optional int32 threadperiod = 7;</code>
     */
    public boolean hasThreadperiod() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 threadperiod = 7;</code>
     */
    public int getThreadperiod() {
      return threadperiod_;
    }

    public static final int USE_FP_FIELD_NUMBER = 8;
    private boolean useFp_;
    /**
     * <code>optional bool use_fp = 8;</code>
     */
    public boolean hasUseFp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool use_fp = 8;</code>
     */
    public boolean getUseFp() {
      return useFp_;
    }

    public static final int CPU_FIELD_NUMBER = 9;
    private int cpu_;
    /**
     * <code>optional int32 cpu = 9;</code>
     */
    public boolean hasCpu() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 cpu = 9;</code>
     */
    public int getCpu() {
      return cpu_;
    }

    public static final int COMP_FIELD_NUMBER = 10;
    private java.lang.Object comp_;
    /**
     * <code>optional string comp = 10;</code>
     */
    public boolean hasComp() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string comp = 10;</code>
     */
    public java.lang.String getComp() {
      java.lang.Object ref = comp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          comp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string comp = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCompBytes() {
      java.lang.Object ref = comp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNC_FIELD_NUMBER = 11;
    private java.lang.Object func_;
    /**
     * <code>optional string func = 11;</code>
     */
    public boolean hasFunc() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string func = 11;</code>
     */
    public java.lang.String getFunc() {
      java.lang.Object ref = func_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          func_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string func = 11;</code>
     */
    public com.google.protobuf.ByteString
        getFuncBytes() {
      java.lang.Object ref = func_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        func_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTNAME_FIELD_NUMBER = 12;
    private java.lang.Object instname_;
    /**
     * <code>optional string instname = 12;</code>
     */
    public boolean hasInstname() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string instname = 12;</code>
     */
    public java.lang.String getInstname() {
      java.lang.Object ref = instname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          instname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string instname = 12;</code>
     */
    public com.google.protobuf.ByteString
        getInstnameBytes() {
      java.lang.Object ref = instname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLAGS_FIELD_NUMBER = 13;
    private int flags_;
    /**
     * <code>optional int32 flags = 13;</code>
     */
    public boolean hasFlags() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 flags = 13;</code>
     */
    public int getFlags() {
      return flags_;
    }

    private void initFields() {
      instance_ = 0;
      modname_ = "";
      rtMsglevel_ = 0;
      userMsglevel_ = 0;
      argv_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      threadname_ = "";
      threadperiod_ = 0;
      useFp_ = false;
      cpu_ = 0;
      comp_ = "";
      func_ = "";
      instname_ = "";
      flags_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInstance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, instance_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getModnameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, rtMsglevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, userMsglevel_);
      }
      for (int i = 0; i < argv_.size(); i++) {
        output.writeBytes(5, argv_.getByteString(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getThreadnameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, threadperiod_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(8, useFp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(9, cpu_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(10, getCompBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, getFuncBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(12, getInstnameBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(13, flags_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, instance_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getModnameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rtMsglevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, userMsglevel_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < argv_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(argv_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getArgvList().size();
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getThreadnameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, threadperiod_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, useFp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, cpu_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getCompBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getFuncBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getInstnameBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, flags_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pb.Rtapicommand.RTAPICommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Rtapicommand.RTAPICommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Rtapicommand.RTAPICommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Rtapicommand.RTAPICommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Rtapicommand.RTAPICommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Rtapicommand.RTAPICommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pb.Rtapicommand.RTAPICommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pb.Rtapicommand.RTAPICommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pb.Rtapicommand.RTAPICommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Rtapicommand.RTAPICommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pb.Rtapicommand.RTAPICommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.RTAPICommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.RTAPICommand)
        pb.Rtapicommand.RTAPICommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Rtapicommand.internal_static_pb_RTAPICommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Rtapicommand.internal_static_pb_RTAPICommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Rtapicommand.RTAPICommand.class, pb.Rtapicommand.RTAPICommand.Builder.class);
      }

      // Construct using pb.Rtapicommand.RTAPICommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        instance_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        modname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        rtMsglevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        userMsglevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        argv_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        threadname_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        threadperiod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        useFp_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        cpu_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        comp_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        func_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        instname_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        flags_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Rtapicommand.internal_static_pb_RTAPICommand_descriptor;
      }

      public pb.Rtapicommand.RTAPICommand getDefaultInstanceForType() {
        return pb.Rtapicommand.RTAPICommand.getDefaultInstance();
      }

      public pb.Rtapicommand.RTAPICommand build() {
        pb.Rtapicommand.RTAPICommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Rtapicommand.RTAPICommand buildPartial() {
        pb.Rtapicommand.RTAPICommand result = new pb.Rtapicommand.RTAPICommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.instance_ = instance_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.modname_ = modname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rtMsglevel_ = rtMsglevel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userMsglevel_ = userMsglevel_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          argv_ = argv_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.argv_ = argv_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.threadname_ = threadname_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.threadperiod_ = threadperiod_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.useFp_ = useFp_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.cpu_ = cpu_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.comp_ = comp_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.func_ = func_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.instname_ = instname_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.flags_ = flags_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Rtapicommand.RTAPICommand) {
          return mergeFrom((pb.Rtapicommand.RTAPICommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Rtapicommand.RTAPICommand other) {
        if (other == pb.Rtapicommand.RTAPICommand.getDefaultInstance()) return this;
        if (other.hasInstance()) {
          setInstance(other.getInstance());
        }
        if (other.hasModname()) {
          bitField0_ |= 0x00000002;
          modname_ = other.modname_;
          onChanged();
        }
        if (other.hasRtMsglevel()) {
          setRtMsglevel(other.getRtMsglevel());
        }
        if (other.hasUserMsglevel()) {
          setUserMsglevel(other.getUserMsglevel());
        }
        if (!other.argv_.isEmpty()) {
          if (argv_.isEmpty()) {
            argv_ = other.argv_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureArgvIsMutable();
            argv_.addAll(other.argv_);
          }
          onChanged();
        }
        if (other.hasThreadname()) {
          bitField0_ |= 0x00000020;
          threadname_ = other.threadname_;
          onChanged();
        }
        if (other.hasThreadperiod()) {
          setThreadperiod(other.getThreadperiod());
        }
        if (other.hasUseFp()) {
          setUseFp(other.getUseFp());
        }
        if (other.hasCpu()) {
          setCpu(other.getCpu());
        }
        if (other.hasComp()) {
          bitField0_ |= 0x00000200;
          comp_ = other.comp_;
          onChanged();
        }
        if (other.hasFunc()) {
          bitField0_ |= 0x00000400;
          func_ = other.func_;
          onChanged();
        }
        if (other.hasInstname()) {
          bitField0_ |= 0x00000800;
          instname_ = other.instname_;
          onChanged();
        }
        if (other.hasFlags()) {
          setFlags(other.getFlags());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInstance()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Rtapicommand.RTAPICommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Rtapicommand.RTAPICommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int instance_ ;
      /**
       * <code>required int32 instance = 1;</code>
       */
      public boolean hasInstance() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 instance = 1;</code>
       */
      public int getInstance() {
        return instance_;
      }
      /**
       * <code>required int32 instance = 1;</code>
       */
      public Builder setInstance(int value) {
        bitField0_ |= 0x00000001;
        instance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 instance = 1;</code>
       */
      public Builder clearInstance() {
        bitField0_ = (bitField0_ & ~0x00000001);
        instance_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object modname_ = "";
      /**
       * <code>optional string modname = 2;</code>
       */
      public boolean hasModname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string modname = 2;</code>
       */
      public java.lang.String getModname() {
        java.lang.Object ref = modname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            modname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string modname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getModnameBytes() {
        java.lang.Object ref = modname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string modname = 2;</code>
       */
      public Builder setModname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        modname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string modname = 2;</code>
       */
      public Builder clearModname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        modname_ = getDefaultInstance().getModname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string modname = 2;</code>
       */
      public Builder setModnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        modname_ = value;
        onChanged();
        return this;
      }

      private int rtMsglevel_ ;
      /**
       * <code>optional int32 rt_msglevel = 3;</code>
       */
      public boolean hasRtMsglevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 rt_msglevel = 3;</code>
       */
      public int getRtMsglevel() {
        return rtMsglevel_;
      }
      /**
       * <code>optional int32 rt_msglevel = 3;</code>
       */
      public Builder setRtMsglevel(int value) {
        bitField0_ |= 0x00000004;
        rtMsglevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rt_msglevel = 3;</code>
       */
      public Builder clearRtMsglevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rtMsglevel_ = 0;
        onChanged();
        return this;
      }

      private int userMsglevel_ ;
      /**
       * <code>optional int32 user_msglevel = 4;</code>
       */
      public boolean hasUserMsglevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 user_msglevel = 4;</code>
       */
      public int getUserMsglevel() {
        return userMsglevel_;
      }
      /**
       * <code>optional int32 user_msglevel = 4;</code>
       */
      public Builder setUserMsglevel(int value) {
        bitField0_ |= 0x00000008;
        userMsglevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 user_msglevel = 4;</code>
       */
      public Builder clearUserMsglevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userMsglevel_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList argv_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArgvIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          argv_ = new com.google.protobuf.LazyStringArrayList(argv_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string argv = 5;</code>
       *
       * <pre>
       * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getArgvList() {
        return argv_.getUnmodifiableView();
      }
      /**
       * <code>repeated string argv = 5;</code>
       *
       * <pre>
       * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
       * </pre>
       */
      public int getArgvCount() {
        return argv_.size();
      }
      /**
       * <code>repeated string argv = 5;</code>
       *
       * <pre>
       * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
       * </pre>
       */
      public java.lang.String getArgv(int index) {
        return argv_.get(index);
      }
      /**
       * <code>repeated string argv = 5;</code>
       *
       * <pre>
       * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
       * </pre>
       */
      public com.google.protobuf.ByteString
          getArgvBytes(int index) {
        return argv_.getByteString(index);
      }
      /**
       * <code>repeated string argv = 5;</code>
       *
       * <pre>
       * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
       * </pre>
       */
      public Builder setArgv(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgvIsMutable();
        argv_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string argv = 5;</code>
       *
       * <pre>
       * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
       * </pre>
       */
      public Builder addArgv(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgvIsMutable();
        argv_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string argv = 5;</code>
       *
       * <pre>
       * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
       * </pre>
       */
      public Builder addAllArgv(
          java.lang.Iterable<java.lang.String> values) {
        ensureArgvIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, argv_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string argv = 5;</code>
       *
       * <pre>
       * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
       * </pre>
       */
      public Builder clearArgv() {
        argv_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string argv = 5;</code>
       *
       * <pre>
       * string argv-type vector; used in MT_RTAPI_APP_* and possibly others
       * </pre>
       */
      public Builder addArgvBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgvIsMutable();
        argv_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object threadname_ = "";
      /**
       * <code>optional string threadname = 6;</code>
       */
      public boolean hasThreadname() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string threadname = 6;</code>
       */
      public java.lang.String getThreadname() {
        java.lang.Object ref = threadname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            threadname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string threadname = 6;</code>
       */
      public com.google.protobuf.ByteString
          getThreadnameBytes() {
        java.lang.Object ref = threadname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          threadname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string threadname = 6;</code>
       */
      public Builder setThreadname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        threadname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string threadname = 6;</code>
       */
      public Builder clearThreadname() {
        bitField0_ = (bitField0_ & ~0x00000020);
        threadname_ = getDefaultInstance().getThreadname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string threadname = 6;</code>
       */
      public Builder setThreadnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        threadname_ = value;
        onChanged();
        return this;
      }

      private int threadperiod_ ;
      /**
       * <code>optional int32 threadperiod = 7;</code>
       */
      public boolean hasThreadperiod() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 threadperiod = 7;</code>
       */
      public int getThreadperiod() {
        return threadperiod_;
      }
      /**
       * <code>optional int32 threadperiod = 7;</code>
       */
      public Builder setThreadperiod(int value) {
        bitField0_ |= 0x00000040;
        threadperiod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 threadperiod = 7;</code>
       */
      public Builder clearThreadperiod() {
        bitField0_ = (bitField0_ & ~0x00000040);
        threadperiod_ = 0;
        onChanged();
        return this;
      }

      private boolean useFp_ ;
      /**
       * <code>optional bool use_fp = 8;</code>
       */
      public boolean hasUseFp() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bool use_fp = 8;</code>
       */
      public boolean getUseFp() {
        return useFp_;
      }
      /**
       * <code>optional bool use_fp = 8;</code>
       */
      public Builder setUseFp(boolean value) {
        bitField0_ |= 0x00000080;
        useFp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool use_fp = 8;</code>
       */
      public Builder clearUseFp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        useFp_ = false;
        onChanged();
        return this;
      }

      private int cpu_ ;
      /**
       * <code>optional int32 cpu = 9;</code>
       */
      public boolean hasCpu() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 cpu = 9;</code>
       */
      public int getCpu() {
        return cpu_;
      }
      /**
       * <code>optional int32 cpu = 9;</code>
       */
      public Builder setCpu(int value) {
        bitField0_ |= 0x00000100;
        cpu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cpu = 9;</code>
       */
      public Builder clearCpu() {
        bitField0_ = (bitField0_ & ~0x00000100);
        cpu_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object comp_ = "";
      /**
       * <code>optional string comp = 10;</code>
       */
      public boolean hasComp() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string comp = 10;</code>
       */
      public java.lang.String getComp() {
        java.lang.Object ref = comp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            comp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string comp = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCompBytes() {
        java.lang.Object ref = comp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string comp = 10;</code>
       */
      public Builder setComp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        comp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string comp = 10;</code>
       */
      public Builder clearComp() {
        bitField0_ = (bitField0_ & ~0x00000200);
        comp_ = getDefaultInstance().getComp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string comp = 10;</code>
       */
      public Builder setCompBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        comp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object func_ = "";
      /**
       * <code>optional string func = 11;</code>
       */
      public boolean hasFunc() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string func = 11;</code>
       */
      public java.lang.String getFunc() {
        java.lang.Object ref = func_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            func_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string func = 11;</code>
       */
      public com.google.protobuf.ByteString
          getFuncBytes() {
        java.lang.Object ref = func_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          func_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string func = 11;</code>
       */
      public Builder setFunc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        func_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string func = 11;</code>
       */
      public Builder clearFunc() {
        bitField0_ = (bitField0_ & ~0x00000400);
        func_ = getDefaultInstance().getFunc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string func = 11;</code>
       */
      public Builder setFuncBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        func_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object instname_ = "";
      /**
       * <code>optional string instname = 12;</code>
       */
      public boolean hasInstname() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string instname = 12;</code>
       */
      public java.lang.String getInstname() {
        java.lang.Object ref = instname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            instname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string instname = 12;</code>
       */
      public com.google.protobuf.ByteString
          getInstnameBytes() {
        java.lang.Object ref = instname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string instname = 12;</code>
       */
      public Builder setInstname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        instname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string instname = 12;</code>
       */
      public Builder clearInstname() {
        bitField0_ = (bitField0_ & ~0x00000800);
        instname_ = getDefaultInstance().getInstname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string instname = 12;</code>
       */
      public Builder setInstnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        instname_ = value;
        onChanged();
        return this;
      }

      private int flags_ ;
      /**
       * <code>optional int32 flags = 13;</code>
       */
      public boolean hasFlags() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 flags = 13;</code>
       */
      public int getFlags() {
        return flags_;
      }
      /**
       * <code>optional int32 flags = 13;</code>
       */
      public Builder setFlags(int value) {
        bitField0_ |= 0x00001000;
        flags_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 flags = 13;</code>
       */
      public Builder clearFlags() {
        bitField0_ = (bitField0_ & ~0x00001000);
        flags_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.RTAPICommand)
    }

    static {
      defaultInstance = new RTAPICommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.RTAPICommand)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_RTAPICommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_RTAPICommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'machinetalk/protobuf/rtapicommand.prot" +
      "o\022\002pb\032!machinetalk/protobuf/nanopb.proto" +
      "\"\367\001\n\014RTAPICommand\022\020\n\010instance\030\001 \002(\005\022\017\n\007m" +
      "odname\030\002 \001(\t\022\023\n\013rt_msglevel\030\003 \001(\005\022\025\n\ruse" +
      "r_msglevel\030\004 \001(\005\022\014\n\004argv\030\005 \003(\t\022\022\n\nthread" +
      "name\030\006 \001(\t\022\024\n\014threadperiod\030\007 \001(\005\022\016\n\006use_" +
      "fp\030\010 \001(\010\022\013\n\003cpu\030\t \001(\005\022\014\n\004comp\030\n \001(\t\022\014\n\004f" +
      "unc\030\013 \001(\t\022\020\n\010instname\030\014 \001(\t\022\r\n\005flags\030\r \001" +
      "(\005:\006\222?\003H\204\007"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor(),
        }, assigner);
    internal_static_pb_RTAPICommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_RTAPICommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_RTAPICommand_descriptor,
        new java.lang.String[] { "Instance", "Modname", "RtMsglevel", "UserMsglevel", "Argv", "Threadname", "Threadperiod", "UseFp", "Cpu", "Comp", "Func", "Instname", "Flags", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
