// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: machinetalk/protobuf/test.proto

package pb;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code pb.TestOpType}
   */
  public enum TestOpType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LINE = 10;</code>
     */
    LINE(0, 10),
    /**
     * <code>CIRCLE = 20;</code>
     */
    CIRCLE(1, 20),
    ;

    /**
     * <code>LINE = 10;</code>
     */
    public static final int LINE_VALUE = 10;
    /**
     * <code>CIRCLE = 20;</code>
     */
    public static final int CIRCLE_VALUE = 20;


    public final int getNumber() { return value; }

    public static TestOpType valueOf(int value) {
      switch (value) {
        case 10: return LINE;
        case 20: return CIRCLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TestOpType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TestOpType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TestOpType>() {
            public TestOpType findValueByNumber(int number) {
              return TestOpType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pb.Test.getDescriptor().getEnumTypes().get(0);
    }

    private static final TestOpType[] VALUES = values();

    public static TestOpType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TestOpType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pb.TestOpType)
  }

  public interface Test1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.Test1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .pb.TestOpType op = 10;</code>
     *
     * <pre>
     * minimum params to encode line or circle
     * </pre>
     */
    boolean hasOp();
    /**
     * <code>required .pb.TestOpType op = 10;</code>
     *
     * <pre>
     * minimum params to encode line or circle
     * </pre>
     */
    pb.Test.TestOpType getOp();

    /**
     * <code>required .pb.EmcPose end = 20;</code>
     */
    boolean hasEnd();
    /**
     * <code>required .pb.EmcPose end = 20;</code>
     */
    pb.Emcclass.EmcPose getEnd();
    /**
     * <code>required .pb.EmcPose end = 20;</code>
     */
    pb.Emcclass.EmcPoseOrBuilder getEndOrBuilder();

    /**
     * <code>optional .pb.PmCartesian center = 30;</code>
     */
    boolean hasCenter();
    /**
     * <code>optional .pb.PmCartesian center = 30;</code>
     */
    pb.Emcclass.PmCartesian getCenter();
    /**
     * <code>optional .pb.PmCartesian center = 30;</code>
     */
    pb.Emcclass.PmCartesianOrBuilder getCenterOrBuilder();

    /**
     * <code>optional .pb.PmCartesian normal = 40;</code>
     */
    boolean hasNormal();
    /**
     * <code>optional .pb.PmCartesian normal = 40;</code>
     */
    pb.Emcclass.PmCartesian getNormal();
    /**
     * <code>optional .pb.PmCartesian normal = 40;</code>
     */
    pb.Emcclass.PmCartesianOrBuilder getNormalOrBuilder();

    /**
     * <code>optional int32 turn = 50;</code>
     */
    boolean hasTurn();
    /**
     * <code>optional int32 turn = 50;</code>
     */
    int getTurn();
  }
  /**
   * Protobuf type {@code pb.Test1}
   */
  public static final class Test1 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.Test1)
      Test1OrBuilder {
    // Use Test1.newBuilder() to construct.
    private Test1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Test1(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Test1 defaultInstance;
    public static Test1 getDefaultInstance() {
      return defaultInstance;
    }

    public Test1 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Test1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 80: {
              int rawValue = input.readEnum();
              pb.Test.TestOpType value = pb.Test.TestOpType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(10, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                op_ = value;
              }
              break;
            }
            case 162: {
              pb.Emcclass.EmcPose.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = end_.toBuilder();
              }
              end_ = input.readMessage(pb.Emcclass.EmcPose.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(end_);
                end_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 242: {
              pb.Emcclass.PmCartesian.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = center_.toBuilder();
              }
              center_ = input.readMessage(pb.Emcclass.PmCartesian.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(center_);
                center_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 322: {
              pb.Emcclass.PmCartesian.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = normal_.toBuilder();
              }
              normal_ = input.readMessage(pb.Emcclass.PmCartesian.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(normal_);
                normal_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 400: {
              bitField0_ |= 0x00000010;
              turn_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Test.internal_static_pb_Test1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Test.internal_static_pb_Test1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Test.Test1.class, pb.Test.Test1.Builder.class);
    }

    public static com.google.protobuf.Parser<Test1> PARSER =
        new com.google.protobuf.AbstractParser<Test1>() {
      public Test1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test1(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Test1> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OP_FIELD_NUMBER = 10;
    private pb.Test.TestOpType op_;
    /**
     * <code>required .pb.TestOpType op = 10;</code>
     *
     * <pre>
     * minimum params to encode line or circle
     * </pre>
     */
    public boolean hasOp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .pb.TestOpType op = 10;</code>
     *
     * <pre>
     * minimum params to encode line or circle
     * </pre>
     */
    public pb.Test.TestOpType getOp() {
      return op_;
    }

    public static final int END_FIELD_NUMBER = 20;
    private pb.Emcclass.EmcPose end_;
    /**
     * <code>required .pb.EmcPose end = 20;</code>
     */
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .pb.EmcPose end = 20;</code>
     */
    public pb.Emcclass.EmcPose getEnd() {
      return end_;
    }
    /**
     * <code>required .pb.EmcPose end = 20;</code>
     */
    public pb.Emcclass.EmcPoseOrBuilder getEndOrBuilder() {
      return end_;
    }

    public static final int CENTER_FIELD_NUMBER = 30;
    private pb.Emcclass.PmCartesian center_;
    /**
     * <code>optional .pb.PmCartesian center = 30;</code>
     */
    public boolean hasCenter() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .pb.PmCartesian center = 30;</code>
     */
    public pb.Emcclass.PmCartesian getCenter() {
      return center_;
    }
    /**
     * <code>optional .pb.PmCartesian center = 30;</code>
     */
    public pb.Emcclass.PmCartesianOrBuilder getCenterOrBuilder() {
      return center_;
    }

    public static final int NORMAL_FIELD_NUMBER = 40;
    private pb.Emcclass.PmCartesian normal_;
    /**
     * <code>optional .pb.PmCartesian normal = 40;</code>
     */
    public boolean hasNormal() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .pb.PmCartesian normal = 40;</code>
     */
    public pb.Emcclass.PmCartesian getNormal() {
      return normal_;
    }
    /**
     * <code>optional .pb.PmCartesian normal = 40;</code>
     */
    public pb.Emcclass.PmCartesianOrBuilder getNormalOrBuilder() {
      return normal_;
    }

    public static final int TURN_FIELD_NUMBER = 50;
    private int turn_;
    /**
     * <code>optional int32 turn = 50;</code>
     */
    public boolean hasTurn() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 turn = 50;</code>
     */
    public int getTurn() {
      return turn_;
    }

    private void initFields() {
      op_ = pb.Test.TestOpType.LINE;
      end_ = pb.Emcclass.EmcPose.getDefaultInstance();
      center_ = pb.Emcclass.PmCartesian.getDefaultInstance();
      normal_ = pb.Emcclass.PmCartesian.getDefaultInstance();
      turn_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getEnd().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(10, op_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(20, end_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(30, center_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(40, normal_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(50, turn_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, op_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(20, end_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(30, center_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(40, normal_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(50, turn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pb.Test.Test1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Test.Test1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Test.Test1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Test.Test1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Test.Test1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Test.Test1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pb.Test.Test1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pb.Test.Test1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pb.Test.Test1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Test.Test1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pb.Test.Test1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.Test1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.Test1)
        pb.Test.Test1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Test.internal_static_pb_Test1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Test.internal_static_pb_Test1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Test.Test1.class, pb.Test.Test1.Builder.class);
      }

      // Construct using pb.Test.Test1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEndFieldBuilder();
          getCenterFieldBuilder();
          getNormalFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        op_ = pb.Test.TestOpType.LINE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (endBuilder_ == null) {
          end_ = pb.Emcclass.EmcPose.getDefaultInstance();
        } else {
          endBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (centerBuilder_ == null) {
          center_ = pb.Emcclass.PmCartesian.getDefaultInstance();
        } else {
          centerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (normalBuilder_ == null) {
          normal_ = pb.Emcclass.PmCartesian.getDefaultInstance();
        } else {
          normalBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        turn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Test.internal_static_pb_Test1_descriptor;
      }

      public pb.Test.Test1 getDefaultInstanceForType() {
        return pb.Test.Test1.getDefaultInstance();
      }

      public pb.Test.Test1 build() {
        pb.Test.Test1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Test.Test1 buildPartial() {
        pb.Test.Test1 result = new pb.Test.Test1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.op_ = op_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (endBuilder_ == null) {
          result.end_ = end_;
        } else {
          result.end_ = endBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (centerBuilder_ == null) {
          result.center_ = center_;
        } else {
          result.center_ = centerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (normalBuilder_ == null) {
          result.normal_ = normal_;
        } else {
          result.normal_ = normalBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.turn_ = turn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Test.Test1) {
          return mergeFrom((pb.Test.Test1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Test.Test1 other) {
        if (other == pb.Test.Test1.getDefaultInstance()) return this;
        if (other.hasOp()) {
          setOp(other.getOp());
        }
        if (other.hasEnd()) {
          mergeEnd(other.getEnd());
        }
        if (other.hasCenter()) {
          mergeCenter(other.getCenter());
        }
        if (other.hasNormal()) {
          mergeNormal(other.getNormal());
        }
        if (other.hasTurn()) {
          setTurn(other.getTurn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOp()) {
          
          return false;
        }
        if (!hasEnd()) {
          
          return false;
        }
        if (!getEnd().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Test.Test1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Test.Test1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private pb.Test.TestOpType op_ = pb.Test.TestOpType.LINE;
      /**
       * <code>required .pb.TestOpType op = 10;</code>
       *
       * <pre>
       * minimum params to encode line or circle
       * </pre>
       */
      public boolean hasOp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .pb.TestOpType op = 10;</code>
       *
       * <pre>
       * minimum params to encode line or circle
       * </pre>
       */
      public pb.Test.TestOpType getOp() {
        return op_;
      }
      /**
       * <code>required .pb.TestOpType op = 10;</code>
       *
       * <pre>
       * minimum params to encode line or circle
       * </pre>
       */
      public Builder setOp(pb.Test.TestOpType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .pb.TestOpType op = 10;</code>
       *
       * <pre>
       * minimum params to encode line or circle
       * </pre>
       */
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        op_ = pb.Test.TestOpType.LINE;
        onChanged();
        return this;
      }

      private pb.Emcclass.EmcPose end_ = pb.Emcclass.EmcPose.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pb.Emcclass.EmcPose, pb.Emcclass.EmcPose.Builder, pb.Emcclass.EmcPoseOrBuilder> endBuilder_;
      /**
       * <code>required .pb.EmcPose end = 20;</code>
       */
      public boolean hasEnd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .pb.EmcPose end = 20;</code>
       */
      public pb.Emcclass.EmcPose getEnd() {
        if (endBuilder_ == null) {
          return end_;
        } else {
          return endBuilder_.getMessage();
        }
      }
      /**
       * <code>required .pb.EmcPose end = 20;</code>
       */
      public Builder setEnd(pb.Emcclass.EmcPose value) {
        if (endBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          end_ = value;
          onChanged();
        } else {
          endBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .pb.EmcPose end = 20;</code>
       */
      public Builder setEnd(
          pb.Emcclass.EmcPose.Builder builderForValue) {
        if (endBuilder_ == null) {
          end_ = builderForValue.build();
          onChanged();
        } else {
          endBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .pb.EmcPose end = 20;</code>
       */
      public Builder mergeEnd(pb.Emcclass.EmcPose value) {
        if (endBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              end_ != pb.Emcclass.EmcPose.getDefaultInstance()) {
            end_ =
              pb.Emcclass.EmcPose.newBuilder(end_).mergeFrom(value).buildPartial();
          } else {
            end_ = value;
          }
          onChanged();
        } else {
          endBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .pb.EmcPose end = 20;</code>
       */
      public Builder clearEnd() {
        if (endBuilder_ == null) {
          end_ = pb.Emcclass.EmcPose.getDefaultInstance();
          onChanged();
        } else {
          endBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .pb.EmcPose end = 20;</code>
       */
      public pb.Emcclass.EmcPose.Builder getEndBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getEndFieldBuilder().getBuilder();
      }
      /**
       * <code>required .pb.EmcPose end = 20;</code>
       */
      public pb.Emcclass.EmcPoseOrBuilder getEndOrBuilder() {
        if (endBuilder_ != null) {
          return endBuilder_.getMessageOrBuilder();
        } else {
          return end_;
        }
      }
      /**
       * <code>required .pb.EmcPose end = 20;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pb.Emcclass.EmcPose, pb.Emcclass.EmcPose.Builder, pb.Emcclass.EmcPoseOrBuilder> 
          getEndFieldBuilder() {
        if (endBuilder_ == null) {
          endBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pb.Emcclass.EmcPose, pb.Emcclass.EmcPose.Builder, pb.Emcclass.EmcPoseOrBuilder>(
                  getEnd(),
                  getParentForChildren(),
                  isClean());
          end_ = null;
        }
        return endBuilder_;
      }

      private pb.Emcclass.PmCartesian center_ = pb.Emcclass.PmCartesian.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pb.Emcclass.PmCartesian, pb.Emcclass.PmCartesian.Builder, pb.Emcclass.PmCartesianOrBuilder> centerBuilder_;
      /**
       * <code>optional .pb.PmCartesian center = 30;</code>
       */
      public boolean hasCenter() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .pb.PmCartesian center = 30;</code>
       */
      public pb.Emcclass.PmCartesian getCenter() {
        if (centerBuilder_ == null) {
          return center_;
        } else {
          return centerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pb.PmCartesian center = 30;</code>
       */
      public Builder setCenter(pb.Emcclass.PmCartesian value) {
        if (centerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          center_ = value;
          onChanged();
        } else {
          centerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.PmCartesian center = 30;</code>
       */
      public Builder setCenter(
          pb.Emcclass.PmCartesian.Builder builderForValue) {
        if (centerBuilder_ == null) {
          center_ = builderForValue.build();
          onChanged();
        } else {
          centerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.PmCartesian center = 30;</code>
       */
      public Builder mergeCenter(pb.Emcclass.PmCartesian value) {
        if (centerBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              center_ != pb.Emcclass.PmCartesian.getDefaultInstance()) {
            center_ =
              pb.Emcclass.PmCartesian.newBuilder(center_).mergeFrom(value).buildPartial();
          } else {
            center_ = value;
          }
          onChanged();
        } else {
          centerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.PmCartesian center = 30;</code>
       */
      public Builder clearCenter() {
        if (centerBuilder_ == null) {
          center_ = pb.Emcclass.PmCartesian.getDefaultInstance();
          onChanged();
        } else {
          centerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .pb.PmCartesian center = 30;</code>
       */
      public pb.Emcclass.PmCartesian.Builder getCenterBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCenterFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pb.PmCartesian center = 30;</code>
       */
      public pb.Emcclass.PmCartesianOrBuilder getCenterOrBuilder() {
        if (centerBuilder_ != null) {
          return centerBuilder_.getMessageOrBuilder();
        } else {
          return center_;
        }
      }
      /**
       * <code>optional .pb.PmCartesian center = 30;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pb.Emcclass.PmCartesian, pb.Emcclass.PmCartesian.Builder, pb.Emcclass.PmCartesianOrBuilder> 
          getCenterFieldBuilder() {
        if (centerBuilder_ == null) {
          centerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pb.Emcclass.PmCartesian, pb.Emcclass.PmCartesian.Builder, pb.Emcclass.PmCartesianOrBuilder>(
                  getCenter(),
                  getParentForChildren(),
                  isClean());
          center_ = null;
        }
        return centerBuilder_;
      }

      private pb.Emcclass.PmCartesian normal_ = pb.Emcclass.PmCartesian.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pb.Emcclass.PmCartesian, pb.Emcclass.PmCartesian.Builder, pb.Emcclass.PmCartesianOrBuilder> normalBuilder_;
      /**
       * <code>optional .pb.PmCartesian normal = 40;</code>
       */
      public boolean hasNormal() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .pb.PmCartesian normal = 40;</code>
       */
      public pb.Emcclass.PmCartesian getNormal() {
        if (normalBuilder_ == null) {
          return normal_;
        } else {
          return normalBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pb.PmCartesian normal = 40;</code>
       */
      public Builder setNormal(pb.Emcclass.PmCartesian value) {
        if (normalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          normal_ = value;
          onChanged();
        } else {
          normalBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .pb.PmCartesian normal = 40;</code>
       */
      public Builder setNormal(
          pb.Emcclass.PmCartesian.Builder builderForValue) {
        if (normalBuilder_ == null) {
          normal_ = builderForValue.build();
          onChanged();
        } else {
          normalBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .pb.PmCartesian normal = 40;</code>
       */
      public Builder mergeNormal(pb.Emcclass.PmCartesian value) {
        if (normalBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              normal_ != pb.Emcclass.PmCartesian.getDefaultInstance()) {
            normal_ =
              pb.Emcclass.PmCartesian.newBuilder(normal_).mergeFrom(value).buildPartial();
          } else {
            normal_ = value;
          }
          onChanged();
        } else {
          normalBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .pb.PmCartesian normal = 40;</code>
       */
      public Builder clearNormal() {
        if (normalBuilder_ == null) {
          normal_ = pb.Emcclass.PmCartesian.getDefaultInstance();
          onChanged();
        } else {
          normalBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .pb.PmCartesian normal = 40;</code>
       */
      public pb.Emcclass.PmCartesian.Builder getNormalBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getNormalFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pb.PmCartesian normal = 40;</code>
       */
      public pb.Emcclass.PmCartesianOrBuilder getNormalOrBuilder() {
        if (normalBuilder_ != null) {
          return normalBuilder_.getMessageOrBuilder();
        } else {
          return normal_;
        }
      }
      /**
       * <code>optional .pb.PmCartesian normal = 40;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pb.Emcclass.PmCartesian, pb.Emcclass.PmCartesian.Builder, pb.Emcclass.PmCartesianOrBuilder> 
          getNormalFieldBuilder() {
        if (normalBuilder_ == null) {
          normalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pb.Emcclass.PmCartesian, pb.Emcclass.PmCartesian.Builder, pb.Emcclass.PmCartesianOrBuilder>(
                  getNormal(),
                  getParentForChildren(),
                  isClean());
          normal_ = null;
        }
        return normalBuilder_;
      }

      private int turn_ ;
      /**
       * <code>optional int32 turn = 50;</code>
       */
      public boolean hasTurn() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 turn = 50;</code>
       */
      public int getTurn() {
        return turn_;
      }
      /**
       * <code>optional int32 turn = 50;</code>
       */
      public Builder setTurn(int value) {
        bitField0_ |= 0x00000010;
        turn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 turn = 50;</code>
       */
      public Builder clearTurn() {
        bitField0_ = (bitField0_ & ~0x00000010);
        turn_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.Test1)
    }

    static {
      defaultInstance = new Test1(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.Test1)
  }

  public interface Test2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.Test2)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code pb.Test2}
   */
  public static final class Test2 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.Test2)
      Test2OrBuilder {
    // Use Test2.newBuilder() to construct.
    private Test2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Test2(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Test2 defaultInstance;
    public static Test2 getDefaultInstance() {
      return defaultInstance;
    }

    public Test2 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Test2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Test.internal_static_pb_Test2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Test.internal_static_pb_Test2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Test.Test2.class, pb.Test.Test2.Builder.class);
    }

    public static com.google.protobuf.Parser<Test2> PARSER =
        new com.google.protobuf.AbstractParser<Test2>() {
      public Test2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test2(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Test2> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pb.Test.Test2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Test.Test2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Test.Test2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Test.Test2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Test.Test2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Test.Test2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pb.Test.Test2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pb.Test.Test2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pb.Test.Test2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Test.Test2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pb.Test.Test2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.Test2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.Test2)
        pb.Test.Test2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Test.internal_static_pb_Test2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Test.internal_static_pb_Test2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Test.Test2.class, pb.Test.Test2.Builder.class);
      }

      // Construct using pb.Test.Test2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Test.internal_static_pb_Test2_descriptor;
      }

      public pb.Test.Test2 getDefaultInstanceForType() {
        return pb.Test.Test2.getDefaultInstance();
      }

      public pb.Test.Test2 build() {
        pb.Test.Test2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Test.Test2 buildPartial() {
        pb.Test.Test2 result = new pb.Test.Test2(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Test.Test2) {
          return mergeFrom((pb.Test.Test2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Test.Test2 other) {
        if (other == pb.Test.Test2.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Test.Test2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Test.Test2) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.Test2)
    }

    static {
      defaultInstance = new Test2(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.Test2)
  }

  public interface Test3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.Test3)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code pb.Test3}
   */
  public static final class Test3 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.Test3)
      Test3OrBuilder {
    // Use Test3.newBuilder() to construct.
    private Test3(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Test3(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Test3 defaultInstance;
    public static Test3 getDefaultInstance() {
      return defaultInstance;
    }

    public Test3 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Test3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Test.internal_static_pb_Test3_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Test.internal_static_pb_Test3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Test.Test3.class, pb.Test.Test3.Builder.class);
    }

    public static com.google.protobuf.Parser<Test3> PARSER =
        new com.google.protobuf.AbstractParser<Test3>() {
      public Test3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test3(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Test3> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pb.Test.Test3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Test.Test3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Test.Test3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Test.Test3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Test.Test3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Test.Test3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pb.Test.Test3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pb.Test.Test3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pb.Test.Test3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pb.Test.Test3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pb.Test.Test3 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.Test3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.Test3)
        pb.Test.Test3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Test.internal_static_pb_Test3_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Test.internal_static_pb_Test3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Test.Test3.class, pb.Test.Test3.Builder.class);
      }

      // Construct using pb.Test.Test3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Test.internal_static_pb_Test3_descriptor;
      }

      public pb.Test.Test3 getDefaultInstanceForType() {
        return pb.Test.Test3.getDefaultInstance();
      }

      public pb.Test.Test3 build() {
        pb.Test.Test3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Test.Test3 buildPartial() {
        pb.Test.Test3 result = new pb.Test.Test3(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Test.Test3) {
          return mergeFrom((pb.Test.Test3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Test.Test3 other) {
        if (other == pb.Test.Test3.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Test.Test3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Test.Test3) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.Test3)
    }

    static {
      defaultInstance = new Test3(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.Test3)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Test1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_Test1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Test2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_Test2_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Test3_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_Test3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037machinetalk/protobuf/test.proto\022\002pb\032#m" +
      "achinetalk/protobuf/emcclass.proto\032!mach" +
      "inetalk/protobuf/nanopb.proto\"\225\001\n\005Test1\022" +
      "\032\n\002op\030\n \002(\0162\016.pb.TestOpType\022\030\n\003end\030\024 \002(\013" +
      "2\013.pb.EmcPose\022\037\n\006center\030\036 \001(\0132\017.pb.PmCar" +
      "tesian\022\037\n\006normal\030( \001(\0132\017.pb.PmCartesian\022" +
      "\014\n\004turn\0302 \001(\005:\006\222?\003H\224\n\"\017\n\005Test2:\006\222?\003H\225\n\"\017" +
      "\n\005Test3:\006\222?\003H\226\n*\"\n\nTestOpType\022\010\n\004LINE\020\n\022" +
      "\n\n\006CIRCLE\020\024"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pb.Emcclass.getDescriptor(),
          fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor(),
        }, assigner);
    internal_static_pb_Test1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_Test1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_Test1_descriptor,
        new java.lang.String[] { "Op", "End", "Center", "Normal", "Turn", });
    internal_static_pb_Test2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_Test2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_Test2_descriptor,
        new java.lang.String[] { });
    internal_static_pb_Test3_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_Test3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_Test3_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    pb.Emcclass.getDescriptor();
    fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
